"""Initial database migration

Revision ID: 001_initial
Revises:
Create Date: 2024-02-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table(
        'users',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('username', sa.String(50), nullable=False),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('avatar_url', sa.String(500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)

    # Create books table
    op.create_table(
        'books',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('title', sa.String(500), nullable=False),
        sa.Column('author', sa.String(255), nullable=True),
        sa.Column('cover_url', sa.String(500), nullable=True),
        sa.Column('file_path', sa.String(500), nullable=False),
        sa.Column('file_type', sa.String(20), nullable=False),
        sa.Column('total_pages', sa.Integer(), nullable=True),
        sa.Column('total_chars', sa.Integer(), nullable=True),
        sa.Column('progress', sa.Float(), nullable=False, default=0.0),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    )
    op.create_index('ix_books_user_id', 'books', ['user_id'])
    op.create_index('ix_books_created_at', 'books', ['created_at'])

    # Create projects table
    op.create_table(
        'projects',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('book_id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='draft'),
        sa.Column('config', sa.JSON(), nullable=False, default={}),
        sa.Column('audio_path', sa.String(500), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    )
    op.create_index('ix_projects_book_id', 'projects', ['book_id'])
    op.create_index('ix_projects_status', 'projects', ['status'])

    # Create scripts table
    op.create_table(
        'scripts',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_id', sa.String(36), nullable=False, unique=True),
        sa.Column('content', sa.JSON(), nullable=False, default=[]),
        sa.Column('status', sa.String(20), nullable=False, default='pending'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    )
    op.create_index('ix_scripts_project_id', 'scripts', ['project_id'], unique=True)

    # Create voice_configs table
    op.create_table(
        'voice_configs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_id', sa.String(36), nullable=False),
        sa.Column('speaker', sa.String(100), nullable=False),
        sa.Column('voice_type', sa.String(20), nullable=False),
        sa.Column('voice_name', sa.String(100), nullable=True),
        sa.Column('style', sa.String(255), nullable=True),
        sa.Column('ref_audio_path', sa.String(500), nullable=True),
        sa.Column('lora_model_path', sa.String(500), nullable=True),
        sa.Column('language', sa.String(20), nullable=False, default='zh-CN'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    )
    op.create_index('ix_voice_configs_project_id', 'voice_configs', ['project_id'])

    # Create chunks table
    op.create_table(
        'chunks',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_id', sa.String(36), nullable=False),
        sa.Column('script_id', sa.String(36), nullable=False),
        sa.Column('speaker', sa.String(100), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('instruct', sa.String(500), nullable=True),
        sa.Column('emotion', sa.String(50), nullable=True),
        sa.Column('section', sa.String(255), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='pending'),
        sa.Column('audio_path', sa.String(500), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    )
    op.create_index('ix_chunks_project_id', 'chunks', ['project_id'])
    op.create_index('ix_chunks_script_id', 'chunks', ['script_id'])
    op.create_index('ix_chunks_status', 'chunks', ['status'])
    op.create_index('ix_chunks_order', 'chunks', ['project_id', 'order_index'])

    # Create highlights table
    op.create_table(
        'highlights',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('book_id', sa.String(36), nullable=False),
        sa.Column('chunk_id', sa.String(36), nullable=True),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('color', sa.String(20), nullable=False),
        sa.Column('start_offset', sa.Integer(), nullable=False),
        sa.Column('end_offset', sa.Integer(), nullable=False),
        sa.Column('chapter', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
        sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    )
    op.create_index('ix_highlights_user_id', 'highlights', ['user_id'])
    op.create_index('ix_highlights_book_id', 'highlights', ['book_id'])
    op.create_index('ix_highlights_chunk_id', 'highlights', ['chunk_id'])

    # Create notes table
    op.create_table(
        'notes',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('highlight_id', sa.String(36), nullable=False, unique=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ),
    )
    op.create_index('ix_notes_highlight_id', 'notes', ['highlight_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('highlights')
    op.drop_table('chunks')
    op.drop_table('voice_configs')
    op.drop_table('scripts')
    op.drop_table('projects')
    op.drop_table('books')
    op.drop_table('users')
    ### end Alembic commands ###
